name: Build RPi Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # This is crucial - set up proper emulation first
    - name: Set up QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static binfmt-support
        sudo systemctl restart systemd-binfmt
    
    - uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          extra-platforms = aarch64-linux
          system-features = nixos-test benchmark big-parallel kvm
    
    - name: Verify emulation works
      run: |
        nix eval --expr 'builtins.currentSystem'
        file /proc/sys/fs/binfmt_misc/qemu-aarch64
    
    - name: Build image
      run: nix build '.#nixosConfigurations.raspberry-pi.config.system.build.sdImage' --print-build-logs
    
    - uses: actions/upload-artifact@v4
      with:
        name: rpi-image
        path: result/sd-image/
