name: Build RPi Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # Set up QEMU for emulation
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
    
    # Install Nix with proper settings
    - uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          extra-platforms = aarch64-linux
          system-features = nixos-test benchmark big-parallel kvm
          # This is crucial - allows system queries
          sandbox = relaxed
    
    # Build with explicit system specification
    - name: Build NixOS image
      run: |
        nix build '.#nixosConfigurations.raspberry-pi.config.system.build.sdImage' \
          --system aarch64-linux \
          --impure \
          --print-build-logs
    
    - uses: actions/upload-artifact@v4
      with:
        name: rpi-image
        path: result/sd-image/
